import type { SceneJSON } from "./schema";

export const mockScene: SceneJSON = {
  steps: [
    {
      title: "Lay out parts",
      caption: "Identify legs, shelf boards, and hardware from the carton.",
      parts: [
        {
          id: "shelf-top",
          label: "Top shelf",
          x: 500,
          y: 140,
          rotationDeg: 0,
          shape: "panel",
          w: 280,
          h: 14,
          d: 100,
          material: "wood",
        },
        {
          id: "side-l",
          label: "Side panel",
          x: 200,
          y: 340,
          rotationDeg: 0,
          shape: "panel",
          w: 14,
          h: 120,
          d: 80,
          material: "wood",
        },
        {
          id: "side-r",
          label: "Side panel",
          x: 700,
          y: 340,
          rotationDeg: 0,
          shape: "panel",
          w: 14,
          h: 120,
          d: 80,
          material: "wood",
        },
        {
          id: "dowels",
          label: "Dowel (\u00d74)",
          x: 460,
          y: 380,
          rotationDeg: 0,
          shape: "dowel",
          material: "wood",
        },
      ],
      confidence: 0.92,
      tools: [],
      warnings: [],
    },
    {
      title: "Attach legs to shelf",
      caption: "Fasten each leg to the shelf corners using the provided bolts.",
      parts: [
        {
          id: "shelf-1",
          label: "Bottom shelf",
          x: 440,
          y: 280,
          rotationDeg: 0,
          shape: "panel",
          w: 260,
          h: 14,
          d: 90,
          material: "wood",
        },
        {
          id: "leg-a",
          label: "Leg A",
          x: 240,
          y: 200,
          rotationDeg: -10,
          shape: "leg",
          w: 22,
          h: 110,
          d: 22,
          material: "wood",
        },
        {
          id: "leg-b",
          label: "Leg B",
          x: 640,
          y: 200,
          rotationDeg: 10,
          shape: "leg",
          w: 22,
          h: 110,
          d: 22,
          material: "wood",
        },
        {
          id: "bolt-1",
          label: "Bolt (\u00d74)",
          x: 500,
          y: 420,
          rotationDeg: 0,
          shape: "screw",
          material: "metal",
        },
      ],
      confidence: 0.88,
      tools: ["Allen key"],
      warnings: ["Do not overtighten bolts."],
    },
    {
      title: "Install back panel",
      caption: "Slide the back panel into the grooves and secure with screws.",
      parts: [
        {
          id: "back",
          label: "Back panel",
          x: 460,
          y: 140,
          rotationDeg: 0,
          shape: "panel",
          w: 240,
          h: 160,
          d: 8,
          material: "wood",
        },
        {
          id: "frame",
          label: "Frame assembly",
          x: 460,
          y: 340,
          rotationDeg: 0,
          shape: "panel",
          w: 260,
          h: 14,
          d: 100,
          material: "wood",
        },
        {
          id: "screw-1",
          label: "Screw (\u00d76)",
          x: 720,
          y: 300,
          rotationDeg: 0,
          shape: "screw",
          material: "metal",
        },
      ],
      confidence: 0.9,
      tools: ["Phillips screwdriver"],
      warnings: [],
    },
  ],
};
