import type { SceneJSON } from "./schema";

/**
 * Simple 4-leg table assembly.
 *
 * Isometric view: depth extends upper-right.
 * When flipped upside-down, legs extend DOWNWARD (higher y values).
 * For back legs, we rotate the perspective so the back edge faces the viewer.
 *
 * Step 1: Lay out all parts
 * Step 2: Flip tabletop, attach front two legs (viewer sees front edge)
 * Step 3: Rotate view, attach back two legs (viewer sees back edge)
 * Step 4: Flip table upright — fully assembled view
 */
export const mockScene: SceneJSON = {
  steps: [
    // ── Step 1: Lay out parts ──────────────────────────────────────────────
    {
      title: "Lay out parts",
      caption:
        "Unpack and identify the tabletop, four legs, and four screws from the box.",
      parts: [
        {
          id: "tabletop",
          label: "Tabletop",
          x: 480,
          y: 180,
          rotationDeg: 0,
          shape: "panel",
          w: 300,
          h: 16,
          d: 160,
          material: "wood",
        },
        {
          id: "leg-fl",
          label: "Front-left leg",
          x: 120,
          y: 370,
          rotationDeg: 0,
          shape: "leg",
          w: 28,
          h: 100,
          d: 28,
          material: "wood",
        },
        {
          id: "leg-fr",
          label: "Front-right leg",
          x: 320,
          y: 370,
          rotationDeg: 0,
          shape: "leg",
          w: 28,
          h: 100,
          d: 28,
          material: "wood",
        },
        {
          id: "leg-bl",
          label: "Back-left leg",
          x: 540,
          y: 370,
          rotationDeg: 0,
          shape: "leg",
          w: 28,
          h: 100,
          d: 28,
          material: "wood",
        },
        {
          id: "leg-br",
          label: "Back-right leg",
          x: 740,
          y: 370,
          rotationDeg: 0,
          shape: "leg",
          w: 28,
          h: 100,
          d: 28,
          material: "wood",
        },
        {
          id: "screws",
          label: "Screws (\u00d74)",
          x: 460,
          y: 440,
          rotationDeg: 0,
          shape: "screw",
          material: "metal",
        },
      ],
      confidence: 0.95,
      tools: [],
      warnings: [],
    },

    // ── Step 2: Attach front legs ──────────────────────────────────────────
    // Tabletop flipped upside-down. Viewer sees front edge.
    // Front holes along the front edge (hy:+4), legs below tabletop.
    {
      title: "Attach front legs",
      caption:
        "Flip the tabletop upside down. Position each front leg at the front corners underneath and drive a screw down into each leg.",
      parts: [
        {
          id: "tabletop",
          label: "Tabletop (flipped)",
          x: 460,
          y: 220,
          rotationDeg: 0,
          shape: "panel",
          w: 300,
          h: 16,
          d: 160,
          material: "wood",
          holes: [
            { hx: -120, hy: 4 },
            { hx: 120, hy: 4 },
          ],
        },
        {
          id: "leg-fl",
          label: "Front-left leg",
          x: 290,
          y: 360,
          rotationDeg: 0,
          shape: "leg",
          w: 28,
          h: 100,
          d: 28,
          material: "wood",
          connectsTo: "tabletop",
        },
        {
          id: "leg-fr",
          label: "Front-right leg",
          x: 630,
          y: 360,
          rotationDeg: 0,
          shape: "leg",
          w: 28,
          h: 100,
          d: 28,
          material: "wood",
          connectsTo: "tabletop",
        },
        {
          id: "screw-fl",
          label: "Screw",
          x: 340,
          y: 60,
          rotationDeg: 0,
          shape: "screw",
          material: "metal",
          insertionTarget: {
            targetPartId: "tabletop",
            angle: 0,
            holeIndex: 0,
          },
        },
        {
          id: "screw-fr",
          label: "Screw",
          x: 580,
          y: 60,
          rotationDeg: 0,
          shape: "screw",
          material: "metal",
          insertionTarget: {
            targetPartId: "tabletop",
            angle: 0,
            holeIndex: 1,
          },
        },
      ],
      confidence: 0.92,
      tools: ["Phillips screwdriver"],
      warnings: ["Do not overtighten — stop when the leg is snug."],
      toolIcons: [
        {
          tool: "phillips_screwdriver",
          x: 870,
          y: 220,
          rotationDeg: -20,
        },
      ],
    },

    // ── Step 3: Rotate view, attach back legs ─────────────────────────────
    // Perspective rotated so the BACK edge now faces the viewer.
    // Front legs already attached appear on the far side (upper area).
    // Back holes are now on the near edge (hy:+4), visible to the viewer.
    {
      title: "Attach back legs",
      caption:
        "Rotate the tabletop so the back edge faces you. Position each back leg at the rear corners underneath and drive a screw down into each leg.",
      parts: [
        {
          id: "tabletop",
          label: "Tabletop (rotated)",
          x: 460,
          y: 220,
          rotationDeg: 0,
          shape: "panel",
          w: 300,
          h: 16,
          d: 160,
          material: "wood",
          holes: [
            { hx: -120, hy: 4 },
            { hx: 120, hy: 4 },
          ],
        },
        {
          id: "leg-fl-done",
          label: "Front leg (attached)",
          x: 560,
          y: 310,
          rotationDeg: 0,
          shape: "leg",
          w: 28,
          h: 80,
          d: 28,
          material: "wood",
        },
        {
          id: "leg-fr-done",
          label: "Front leg (attached)",
          x: 720,
          y: 310,
          rotationDeg: 0,
          shape: "leg",
          w: 28,
          h: 80,
          d: 28,
          material: "wood",
        },
        {
          id: "leg-bl",
          label: "Back-left leg",
          x: 290,
          y: 360,
          rotationDeg: 0,
          shape: "leg",
          w: 28,
          h: 100,
          d: 28,
          material: "wood",
          connectsTo: "tabletop",
        },
        {
          id: "leg-br",
          label: "Back-right leg",
          x: 630,
          y: 360,
          rotationDeg: 0,
          shape: "leg",
          w: 28,
          h: 100,
          d: 28,
          material: "wood",
          connectsTo: "tabletop",
        },
        {
          id: "screw-bl",
          label: "Screw",
          x: 340,
          y: 60,
          rotationDeg: 0,
          shape: "screw",
          material: "metal",
          insertionTarget: {
            targetPartId: "tabletop",
            angle: 0,
            holeIndex: 0,
          },
        },
        {
          id: "screw-br",
          label: "Screw",
          x: 580,
          y: 60,
          rotationDeg: 0,
          shape: "screw",
          material: "metal",
          insertionTarget: {
            targetPartId: "tabletop",
            angle: 0,
            holeIndex: 1,
          },
        },
      ],
      confidence: 0.92,
      tools: ["Phillips screwdriver"],
      warnings: [],
      toolIcons: [
        {
          tool: "phillips_screwdriver",
          x: 870,
          y: 220,
          rotationDeg: -20,
        },
      ],
    },

    // ── Step 4: Flip upright — fully assembled ─────────────────────────────
    {
      title: "Stand upright",
      caption:
        "Carefully flip the table over so it rests on its four legs. Verify it sits level on the floor.",
      parts: [
        {
          id: "tabletop",
          label: "Tabletop",
          x: 460,
          y: 150,
          rotationDeg: 0,
          shape: "panel",
          w: 300,
          h: 16,
          d: 160,
          material: "wood",
        },
        {
          id: "leg-fl",
          label: "Leg",
          x: 340,
          y: 280,
          rotationDeg: 0,
          shape: "leg",
          w: 28,
          h: 100,
          d: 28,
          material: "wood",
        },
        {
          id: "leg-fr",
          label: "Leg",
          x: 580,
          y: 280,
          rotationDeg: 0,
          shape: "leg",
          w: 28,
          h: 100,
          d: 28,
          material: "wood",
        },
        {
          id: "leg-bl",
          label: "Leg",
          x: 430,
          y: 230,
          rotationDeg: 0,
          shape: "leg",
          w: 28,
          h: 100,
          d: 28,
          material: "wood",
        },
        {
          id: "leg-br",
          label: "Leg",
          x: 670,
          y: 230,
          rotationDeg: 0,
          shape: "leg",
          w: 28,
          h: 100,
          d: 28,
          material: "wood",
        },
      ],
      confidence: 0.95,
      tools: [],
      warnings: [],
    },
  ],
};
